Niwas/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('user.urls')),
    path('',include('allauth.urls')),
    path('',include('properties.urls')),
]

urlpatterns+=static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

properties/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('create-property',views.createProperty,name='create-property'),
    path('add-kitchen',views.addKitchen,name='add-kitchen'),
    path('add-bathroom/<str:pk>',views.addBathroom,name='add-bathroom'),
     path('delete-property/<str:pk>',views.deleteProperty,name='delete-property'),
    path('add-room/<str:pk>',views.addRooms,name='add-room'),
    path('add-images/<str:pk>',views.addImages,name='add-images'),
    path('add-video/<str:pk>',views.addVideo,name='add-video'),
    path('get-images/',views.getImages,name='get-images'),
    path('properties-list/',views.propertyList,name='properties-list'),
    path('cancel-property-creation/<str:pk>',views.cancelPorpertyCreation,name='cancel-property-creation'),
    path('show-property/<str:pk>',views.showProperty,name='show-property'),
    path('book-property/<str:pk>',views.bookProperty,name='book-property'),
     path('delete-booking/<str:pk>',views.deleteBooking,name='delete-booking'),
]

user/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('user-login/',views.userLogin,name="user-login"),
    path('new-user-register/',views.newUserRegister,name="new-user-register"),
    path('',views.welcomePage,name="welcome-page"),
    path('social/signup/',views.signupRedirect,name="signup-redirect"),
    path('logout-user/',views.logOutUser,name="logout-user"),
    path('google-login-portal/',views.googleLoginPortal,name='google-login-portal'),
    path('create-new-agent',views.createNewAgent,name='create-new-agent'),
    path('create-new-tenant',views.createNewTenant,name='create-new-tenant'),
    path('complete-tenant-profile/<str:pk>',views.completeTenantProfile,name='complete-tenant-profile'),
    path('test-template',views.testTemplate,name='test-template'),
    path('view-agent-profile/',views.viewAgentProfile,name='view-agent-profile'),
    path('view-bookings/',views.viewBookings,name='view-bookings'),
    path('view-tenant-profile/',views.viewTenantProfile,name='view-tenant-profile'),
    path('view-profile/',views.viewProfile,name='view-profile'),
    path('complete-agent-profile/<str:pk>',views.completeAgentProfile,name='complete-agent-profile'),
]

properties/models.py
from django.db import models
from user.models import AgentUserProfile,TenantUserProfile
from django.core.validators import MaxValueValidator

import uuid
# Create your models here.

class Category(models.Model):
    
    TYPE_CHOICES=(
        ('SR','Single Room'),
        ('DR','Double Room'),
        ('1BHK','One bedroom, hall and Kitchen'),
        ('2BHK','Two bedroom, hall and Kitchen'),
        ('3BHK','Three bedroom, hall and Kitchen'),
        ('4BHK','four bedroom, hall and Kitchen'),
        )
    id=models.UUIDField(default=uuid.uuid4,unique=True,primary_key=True,editable=False)
    name=models.CharField(max_length=5,choices=TYPE_CHOICES,default='1BHK')
    def __str__(self) -> str:
        return self.name


    
class Property(models.Model):
    CITY_CHOICES=(
    ('KTM','Kathmandu'),
    ('PK','Pokhara'),
    ('BT','Butwal'),
    ('BTM','Birtamode'),
    ('BTG','Biratnagar'),
    ('DH','Dharan'),
)
    PARKING_CHOICES=(
        ('NONE','None'),
        ('2W','Two Wheeler'),
        ('4W','Four Wheeler'),
    )
    WATER_CHOICES=(
        ('NONE','None'),
        ('A','Anytime'),
        ('B','Boring Water'),
        ('T','Tank Water'),
    )
    STATUS_CHOICES=(
        ('OS','On sale'),
        ('S','Sold'),
    )
    title=models.CharField(max_length=200)
    status=models.CharField(max_length=5,choices=STATUS_CHOICES,default='OS')
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    id=models.UUIDField(default=uuid.uuid4,unique=True,primary_key=True,editable=False)
    description=models.TextField(null=True,blank=True)
    featured_image=models.ImageField(blank=True,upload_to='image/',default='image/city.jpeg')
    created=models.DateTimeField(auto_now_add=True)
    agent=models.ForeignKey(AgentUserProfile,on_delete=models.CASCADE,null=True)
    price= models.DecimalField(max_digits=10, decimal_places=2)
    city=models.CharField(max_length=5,choices=CITY_CHOICES,default='KTM')
    address=models.CharField(max_length=200,null=True)
    parking=models.CharField(max_length=5,choices=PARKING_CHOICES,default='1BHK')
    water=models.CharField(max_length=5,choices=WATER_CHOICES,default='NONE')
    views=models.IntegerField(default=0,blank=True)
    reservations=models.IntegerField(default=0,blank=True)
    def __str__(self) -> str:
        return self.title

    def add_view(self):
        self.views+=1
    
    def add_booking(self):
        self.reservations+=1
    
class Kitchen(models.Model):
    TYPE_CHOICES=(
        ('N','Not Available'),
        ('SEP','Separated'),
        ('AT','Attached')
    )

    id=models.UUIDField(default=uuid.uuid4,unique=True,primary_key=True,editable=False)
    type=models.CharField(max_length=5,choices=TYPE_CHOICES,default='SEP')
    property=models.ForeignKey(Property,on_delete=models.CASCADE,null=True)
    image=models.ImageField(upload_to='image/',blank=True,default='image/noimage.png')

class Bathroom(models.Model):
    TYPE_CHOICES=(
        ('SHR','Shared'),
        ('SEP','Separated')
    )
    id=models.UUIDField(default=uuid.uuid4,unique=True,primary_key=True,editable=False)
    property=models.ForeignKey(Property,on_delete=models.CASCADE,null=True)
    type=models.CharField(max_length=5,choices=TYPE_CHOICES,default='SEP')
    image=models.ImageField(upload_to='image/',blank=True,default='image/noimage.png')

class Bedroom(models.Model):
    id=models.UUIDField(default=uuid.uuid4,unique=True,primary_key=True,editable=False)
    numbers=models.PositiveIntegerField(default=1, validators=[MaxValueValidator(100)],null=True)
    property=models.ForeignKey(Property,on_delete=models.CASCADE,null=True)


class BedroomImage(models.Model):
     id=models.UUIDField(default=uuid.uuid4,unique=True,primary_key=True,editable=False)
     bedroom=models.ForeignKey(Bedroom,on_delete=models.CASCADE)
     image=models.ImageField(upload_to='image/')

     def __str__(self):
        return str(self.image)

class Video(models.Model):
    name= models.CharField(max_length=500)
    videofile= models.FileField(upload_to='video/', null=True, blank=True,verbose_name="")

    def __str__(self):
        return self.name + ": " + str(self.videofile)
class VideoTour(models.Model):
    name= models.CharField(max_length=500)
    property=models.ForeignKey(Property,on_delete=models.CASCADE,null=True)
    videofile= models.FileField(upload_to='video/', null=True, blank=True,verbose_name="")

    def __str__(self):
        return str(self.videofile)

class Bookings(models.Model):
    id=models.UUIDField(default=uuid.uuid4,unique=True,primary_key=True,editable=False)
    created=models.DateTimeField(auto_now_add=True)
    tenant=models.ForeignKey(TenantUserProfile,on_delete=models.PROTECT)
    property=models.ForeignKey(Property,on_delete=models.PROTECT)

properties/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from django.core.paginator import Paginator
from django.http import HttpResponse
from user.forms import CustomUserCreationForm
from user.models import TenantUserProfile,AgentUserProfile,CustomUser
from .utils import getAgentFromUser,getTenantFromUser
from .forms import *
from django.contrib.auth.decorators import login_required

@login_required(login_url='/user-login')
def deleteProperty(request,pk):
    property=Property.objects.get(id=pk)
    agent=getAgentFromUser(request.user)
    if property.agent==agent:
        property.delete()
        messages.success(request,'Property has been deleted.')
        return redirect('/')
    else:
        messages.error(request,'Property could not be deleted.')
        return redirect('/')

@login_required(login_url='/user-login')
def deleteBooking(request,pk):
    booking=Bookings.objects.get(id=pk)
    tenant=booking.tenant
    userTenant=getTenantFromUser(request.user)
    if tenant==userTenant:
        booking.delete()
        return redirect('/')
    else:
        return redirect('/')
@login_required(login_url='/user-login')
def bookProperty(request,pk):
    tenant=getTenantFromUser(request.user)
    property=Property.objects.get(id=pk)
    
    duplicate_list=Bookings.objects.filter(tenant=tenant,property=property)
    if len(duplicate_list)>0:
        messages.error(request,'You have booked this property already')
        return redirect('properties-list')
    booking=Bookings.objects.create(tenant=tenant,property=property)
    booking.save()
    property.add_booking()
    property.save()
    messages.success(request,'Booked Successfully')
    return redirect('welcome-page') 
def getImages(request):
    return render(request,'properties/get-images.html')

def showProperty(request,pk):
    property=Property.objects.get(id=pk)
    property.add_view()
    property.save()
    kitchen=Kitchen.objects.get(property=property)
    bathroom=Bathroom.objects.get(property=property)
    videoTour=VideoTour.objects.get(property=property)
    bedroom=Bedroom.objects.get(property=property)
    hasTour=str(videoTour.videofile) !=""
    images=BedroomImage.objects.filter(bedroom=bedroom)
    isBookmarked=False
    if request.user.is_authenticated:
        if getTenantFromUser(request.user) is not None:
            bookmark=Bookings.objects.filter(tenant=getTenantFromUser(request.user),property=property)
            isBookmarked=len(bookmark)>0
    print(isBookmarked)
    context={
        'property':property,
        'kitchen':kitchen,
        'bathroom':bathroom,
        'tourAvailable':hasTour,
        'videotour':videoTour,
        'images':images,
        'isBookmarked':isBookmarked
    }
    return render(request,'properties/show-property.html',context)

def propertyList(request):
    page=request.GET.get('page')
    city_code={
        'Kathmandu':'KTM',
        'Pokhara':'PK',
        'Butwal':'BT',
        'Birtamode':'BTM',
        'Biratnagar':'BTG',
        'Dharan':'DH'
    }
    if request.method=='POST':
        print('at POST')
        type=Category.objects.get(name=request.POST.get('type'))
        city=city_code[request.POST.get('city')]
        address=request.POST.get('address')
        minPrice=request.POST.get('min-price')
        maxPrice=request.POST.get('max-price')
        try:
            property_list=Property.objects.filter(status='OS',category=type,city=city,address__icontains=address).filter(price__range=(minPrice,maxPrice)).order_by('price')
        except:
            messages.error(request,'fill all the information correctly')
            return redirect('prpperties-list')
        if len(property_list)==0:
            print('not found any')
            return render(request,'properties/empty-page.html')
        else:
            paginator=Paginator(property_list,per_page=15)
            page_object=paginator.get_page(page)
            context={'properties':page_object,'total_pages':paginator.page_range}
            return render(request,'properties/property-list.html',context) 

    properties=Property.objects.filter(status='OS').order_by('price')
    if len(properties)==0:
        return render(request,'properties/empty-page.html')
    else:
        paginator=Paginator(properties,per_page=15)
        page_object=paginator.get_page(page)
        context={'properties':page_object,'total_pages':paginator.page_range}
        print(page)
        return render(request,'properties/property-list.html',context)

def cancelPorpertyCreation(request,pk):
    temp_property=Property.objects.get(id=pk)
    temp_property.delete()
    Kitchen.objects.filter(property__isnull=True).delete()
    Bathroom.objects.filter(property__isnull=True).delete()
    Bedroom.objects.filter(property__isnull=True).delete()
    return redirect('create-property')
@login_required(login_url='/user-login')
def addVideo(request,pk):
    print('inside add video view')
    if request.method=='POST':
        form=VideoForm(request.POST,request.FILES)
        if form.is_valid():
            print('Image form is valid')
            video=form.save()
            property=Property.objects.get(id=pk)
            video.property=property
            video.save()
            return render(request,'properties/done.html')
        else:
            messages.error(request,'Please fill the details correctly')
            context={'form':PropertyForm()}
            return render(request,'properties/create-properties.html',context)
    else:
        form=VideoForm()
        property=Property.objects.get(id=pk)
        context={'form':form,'property':property}
        return render(request,'properties/add-video.html',context)
    
@login_required(login_url='/user-login')
def addImages(request,pk):
   
    if request.method=='POST':
        property=Property.objects.get(id=pk)
        if request.FILES.get('imageFile') is None:
            messages.error(request,'please choose at least one image')
            context={'property':property}
            return render(request,'properties/add-rooms.html',context)
        print('Image form is valid')
       
        bedroom=Bedroom.objects.get(property=property)
        property.featured_image=request.FILES.get('imageFile')
        
        property.save()
        bedImage=BedroomImage.objects.create(bedroom=bedroom,image=request.FILES.get('imageFile'))
        bedImage.save()
        context={'property':property}
        messages.success(request,"image added successfully")
        return render(request,'properties/add-rooms.html',context)
        
@login_required(login_url='/user-login')
def addRooms(request,pk):
    if request.method=='POST':
        room_number={
            'SR':1,
            'DR':2,
            '1BHK':1,
            '2BHK':2,
            '3BHK':3,
            '4BHK':4,
        }
        form=BathroomForm(request.POST,request.FILES)
        if form.is_valid():
            print('Bathroom form is valid')
            bathroom=form.save()
            property=Property.objects.get(id=pk)
            bathroom.property=property
            bathroom.save()
            bedroom=Bedroom.objects.create(numbers=room_number[str(property.category)],property=property)
            bedroom.save()
            form=BedroomImageForm()
            context={'form':form,'property':property}
            return render(request,'properties/add-rooms.html',context)
        else:
            messages.error(request,'Please fill the details correctly')
            context={'form':PropertyForm()}
            return render(request,'properties/create-properties.html',context)

@login_required(login_url='/user-login')
def addBathroom(request,pk):
    if request.method=='POST':
        form=KitchenForm(request.POST,request.FILES)
        if form.is_valid():
            print('kitchen form is valid')
            kitchen=form.save()
            property=Property.objects.get(id=pk)
            kitchen.property=property
            kitchen.save()
            form=BathroomForm()
            context={'property':property,'form':form}
            return render(request,'properties/add-bathroom.html',context)
        else:
            messages.error(request,'Please fill the details correctly')
            context={'form':PropertyForm()}
            return render(request,'properties/create-properties.html',context)

@login_required(login_url='/user-login')
def addKitchen(request):
    if request.method=='POST':
        form=PropertyForm(request.POST)
        if form.is_valid():
            agent=getAgentFromUser(request.user)
            saved_property=form.save()
            saved_property.agent=agent
            saved_property.save()
            form=KitchenForm()
            context={'property':saved_property,'form':form}
            return render(request,'properties/add-kitchen.html',context)
        else:
            messages.error(request,'Please fill the details correctly')
            context={'form':form}
            return render(request,'properties/create-properties.html',context)

@login_required(login_url='/user-login')
def createProperty(request):
    if getAgentFromUser(request.user) is None:
        messages.error(request,'You must be  registered agent to post properties.')
        return redirect('/')
    form=PropertyForm()
    context={'form':form}
    return render(request,'properties/create-properties.html',context)

properties/templates/properties/add-bathroom.html
{% extends 'welcomepage.html' %}
{% load static %}
{% block title %}Add bathroom details{% endblock %}
{% block content %}
<section class="hero is-small has-background-dark  pr-3 pl-2 pb-2 mt-5">
    <div class="hero-body">
      <p class="title has-text-white">
        Add details to Bathroom
      </p>
      <p class="subtitle has-text-white">
        People are really sensitive about this 
      </p>
    </div>
    <progress class="progress is-primary" value="60" max="100">15%</progress>
  </section>
<div class="column is-half is-offset-one-quarter mt-3 ">
    <form method="POST" action="{% url 'add-room' property.id %}" enctype='multipart/form-data'>
        {% csrf_token %}
        <div class='box type-field-container'>
            <div class="field">
                <label class="label">Type</label>
                <div class="radio-wrapper">
                {% for radio in form.type %}
                {{radio}}
                {% endfor %}
                </div>             
            </div>
        </div>

        <div class='box type-field-container'>
            <div class="field">
                <h3 class="subtitle is-3">Now choose an Image for the bathroom</h3>
                <h6 class="subtitle is-6">Make sure the angle is good and the Image is clean</h6>
                <div class="file is-info has-name">
                    <label class="file-label">
                      {{form.image}}
                      <span class="file-cta">
                        <span class="file-icon">
                          <i class="fas fa-upload"></i>
                        </span>
                        <span class="file-label">
                          Choose an Image
                        </span>
                      </span>
                      <span class="file-name">
                        
                      </span>
                    </label>
                  </div> 
            </div>
        </div>
       
          <button type="submit" class="button is-black">Next</button>
          
      
    </form>
    <a href="{% url 'cancel-property-creation' property.id %}"><button class="button is-danger mt-2">Cancel</button></a> 
</div>
{% endblock %}

properties/templates/properties/add-kitchen.html
{% extends 'welcomepage.html' %}
{% load static %}
{% block title %}Add Kitcken details{% endblock %}
{% block content %}
<section class="hero is-small has-background-dark  pr-3 pl-2 pb-2 mt-5">
    <div class="hero-body">
      <p class="title has-text-white">
        Add details to kitchen
      </p>
      <p class="subtitle has-text-white">
        This might be a deal breaker
      </p>
    </div>
    <progress class="progress is-primary" value="40" max="100">15%</progress>
  </section>
<div class="column is-half is-offset-one-quarter mt-3 ">
    <form method="POST" action="{% url 'add-bathroom' property.id %}" enctype='multipart/form-data'>
        {% csrf_token %}
        <div class='box type-field-container'>
            <div class="field">
                <label class="label">Type</label>
                <div class="radio-wrapper">
                {% for radio in form.type %}
                {{radio}}
                {% endfor %}
                </div>             
            </div>
        </div>

        <div class='box type-field-container'>
            <div class="field">
                <h3 class="subtitle is-3">Now choose an Image for the Kitchen</h3>
                <h6 class="subtitle is-6">Make sure the angle is good, and the Image is clean</h6>
                <div class="file is-info has-name">
                    <label class="file-label">
                      {{form.image}}
                      <span class="file-cta">
                        <span class="file-icon">
                          <i class="fas fa-upload"></i>
                        </span>
                        <span class="file-label">
                          Choose an Image
                        </span>
                      </span>
                      <span class="file-name">
                        
                      </span>
                    </label>
                  </div> 
            </div>
        </div>
        
          <button type="submit" class="button is-black">Next</button>
          
        
      </form>
      <a href="{% url 'cancel-property-creation' property.id %}"><button class="button is-danger mt-2">Cancel</button></a>
</div>
{% endblock %}

properties/templates/properties/add-rooms.html
{% extends 'welcomepage.html' %}
{% load static %}
{% block title %}Add rooms to property{% endblock %}
{% block content %}

<section class="hero is-small has-background-dark  pr-3 pl-2 pb-2 mt-5">
    <div class="hero-body">
      <p class="title has-text-white">
        Time to upload Images for other rooms
      </p>
      <p class="subtitle has-text-white">
        This is important as well
      </p>
    </div>
    <progress class="progress is-primary" value="80" max="100">15%</progress>
  </section>
<div class="column is-half is-offset-one-quarter mt-3 ">
    <form method="POST" action="{% url 'add-images' property.id %}" enctype='multipart/form-data'>
        {% csrf_token %}

        <div class='box type-field-container'>
            <div class="field">
                <h3 class="subtitle is-3">Now choose an Image for the Bedroom/rooms</h3>
                <h6 class="subtitle is-6">Make sure the angle is good, and the Image is clean</h6>
                <div class="file is-normal">
                  <label class="file-label">
                    <input class="file-input" type="file" name="imageFile">
                    <span class="file-cta">
                      <span class="file-icon">
                        <i class="fas fa-upload"></i>
                      </span>
                      <span class="file-label">
                        Choose Image
                      </span>
                    </span>
                  </label>
                </div>
            </div>
        </div>
        
          <button type="submit" class="button is-black">Add photo</button>
         
        
        </form>
        <a href="{% url 'add-video' property.id %}"><button class="button is-primary mt-2">Move on</button></a>
</div>
{% endblock %}

properties/templates/properties/add-video.html
{% extends 'welcomepage.html' %}
{% load static %}
{% block title %}Add video Tour to property{% endblock %}
{% block content %}

<section class="hero is-small has-background-dark  pr-3 pl-2 pb-2 mt-5">
    <div class="hero-body">
      <p class="title has-text-white">
        Upload a video tour
      </p>
      <p class="subtitle has-text-white">
        It's only second to visiting in person
      </p>
    </div>
    <progress class="progress is-primary" value="100" max="100">15%</progress>
  </section>
<div class="column is-half is-offset-one-quarter mt-3 ">
    <form method="POST" action="" enctype='multipart/form-data'>
        {% csrf_token %}

        <div class='box type-field-container'>
            <div class="field">
                <h3 class="subtitle is-3">Video tour</h3>
                <h6 class="subtitle is-6">lightning and video stability</h6>
                <div class="file is-info has-name">
                    <label class="file-label">
                      {{form.videofile}}
                      <span class="file-cta">
                        <span class="file-icon">
                          <i class="fas fa-upload"></i>
                        </span>
                        <span class="file-label">
                          Choose a Video
                        </span>
                      </span>
                      <span class="file-name">
                        
                      </span>
                    </label>
                  </div> 
            </div>
        </div>
        <button type="submit" class="button is-black">Done</button>
    </form>
    
</div>

{% endblock %}

properties/templates/properties/done.html
{% extends 'welcomepage.html' %}
{% load static %}
{% block title %}New property added{% endblock%}
{% block content %}
<div class="column is-three-fifths is-offset-one-fifth mt-6">
    <div class="column card-container-div">
        <div class="content-div">
            <h4 class="subtitle is-4">New Property added <br>Happy dealing!!</h4>
            <a href="{% url 'welcome-page' %}"><button class="button is-light">Go to Home</button></a>
        </div>
        <img class="success-image" src="{% static 'image/success.jpeg' %}" height='600' width='400'>
        
    </div>
</div>
    
{% endblock %}

properties/templates/properties/show-property.html
{% extends 'welcomepage.html' %}
{% load static %}
{% block title %}Show property{% endblock%}
{% block content %}
<div class="column is-full mt-6 ">
    <h2 class="title is-2 has-text-centered mb-6">{{property.title|capfirst}}</h2>
    
    <div class="columns mt-6">
        <div class="column is-one-fifths ml-3 ">
            <img class="ui fluid image" src="{{property.featured_image.url}}">
        </div>
     
        <div class="column is-two-fifths has-text-centered mr-3 ">
           <h4 class="subtitle is-4 has-text-justified is-italic">{{property.description}}</h4>
        </div>
       
      </div>

</div>
<div class="ui divider"></div>
<div class="column is-full mt-2 ">
    <h4 class="title is-4 has-text-centered">Details</h4>
    <div class="columns  pt-4 pl-4 pr-4 has-text-centered">
        <div class="column">
            <div class="ui tiny statistic">
                <div class="label">
                  Type
                </div>
                <div class="value">
                  {{property.category.name}}
                </div>
              </div>
          </div>
          <div class="column">
            <div class="ui tiny violet statistic">
                <div class="label">
                  Price
                </div>
                <div class="value">
                    <i class="money bill alternate outline icon"></i> {{property.price}}
                </div>
              </div>
          </div>
          
            <div class="column">
              
                  <div class="ui tiny statistic">
                    <div class="label">
                      City
                    </div>
                    <div class="value">
                        <i class="building icon"></i> {{property.get_city_display}}
                    </div>
                  </div>
              </div>
              </div>
    </div>
    <div class="column is-full has-text-centered">
        <div class="ui tiny  statistic">
            <div class="label">
              Address
            </div>
            <div class="value">
                <i class="map marker icon"></i> {{property.address}}
            </div>
          </div>
      <div class="ui divider"></div>
      <div class="column is-full mt-2 ">
        <h4 class="title is-4 has-text-centered">Kitchen</h4>
        <div class="column is-three-fifths is-offset-one-fifth">
          {% if kitchen.image %}
          <img class="ui fluid image" src="{{kitchen.image.url}}">
          {% endif %}
          <div class="column has-text-centered">
            <div class="ui tiny statistic">
                <div class="label">
                  Type
                </div>
                <div class="value">
                  
                  {{kitchen.get_type_display}}
                  
                </div>
              </div>
          </div>
        </div>
      </div>
      <div class="ui divider"></div>
      <div class="column is-full mt-2 ">
        <h4 class="title is-4 has-text-centered">Bathroom</h4>
        <div class="column is-three-fifths is-offset-one-fifth">
          
          <img class="ui fluid image" src="{{bathroom.image.url}}">

          <div class="column has-text-centered">
            <div class="ui tiny statistic">
                <div class="label">
                  Type
                </div>
                <div class="value">
                  
                  {{bathroom.get_type_display}}
                  
                </div>
              </div>
          </div>
        </div>
      </div>
      <div class="ui divider"></div>
      <div class="column is-full mt-2 ">
        <h4 class="title is-4 has-text-centered">Water and Parking</h4>
        <div class="columns mt-6">
          <div class="column">
            <div class="ui tiny statistic">
              <div class="label">
                Water
              </div>
              <div class="value">
                
                {{property.get_water_display}}
                
              </div>
            </div>
          </div>
          
          <div class="column">
            <div class="ui tiny statistic">
              <div class="label">
                Parking
              </div>
              <div class="value">
                
                {{property.get_parking_display}}
                
              </div>
            </div>
          </div>
         
        </div>
      </div>
      <div class="ui divider"></div>
      <div class="column is-full mt-2 ">
        <h4 class="title is-4 has-text-centered">Images</h4>
        <div class="ui tiny images">
         {% for image in images %}
         <img class="ui image js-modal-trigger carousal" src="{{image.image.url}}" data-target="{{image.image.url}}">
         {% endfor %} 
        </div>
         {% for image in images %}
         <div id="{{image.image.url}}" class="modal">
          <div class="modal-background"></div>
          <div class="modal-content">
            <p class="image is-4by3">
              <img src="{{image.image.url}}" alt="">
            </p>
          </div>
          <button class="modal-close is-large" aria-label="close"></button>
        </div>
        {% endfor %}
      </div>
      <div class="ui divider"></div>
      {% if tourAvailable %}
      <div class="column is-full mt-2 ">
        <h4 class="title is-4 has-text-centered">Take a video Tour</h4>
        <div class="column is-three-fifths is-offset-one-fifth">
          <div class="box has-background-black">
            <video class="tour" controls>
              <source src="{{ videotour.videofile.url }}"  type="video/mp4">
            </video>
          </div>
          
      </div>
      </div>
      {%  endif %}
      <div class="ui divider"></div>
      {% if user.type == 'T' and isBookmarked != True %}
      <a href="{% url 'book-property' property.id %}"><div class="ui animated fade button massive red" tabindex="0">
        <div class="visible content">Request for appointment</div>
        <div class="hidden content">
        Charges Apply
        </div>
      </div></a>
      {% endif %}
  </div>
    
{% endblock %}